struct FrameUniforms {
    // x = width, y = height, z = time, w = projected-grid cell count.
    resolution_time_grid: vec4<f32>,
    view_proj: mat4x4<f32>,

    // xyz = camera position, w = tan(vertical_fov / 2).
    camera_pos_fov: vec4<f32>,
    // xyz = camera right, w = max projected distance.
    camera_right_maxdist: vec4<f32>,
    // xyz = camera up, w = aspect ratio.
    camera_up_aspect: vec4<f32>,
    // xyz = camera forward, w = water plane height.
    camera_forward_water: vec4<f32>,

    // x = grid snap, y = chop scale, z = foam gain, w = detail gain.
    water_params0: vec4<f32>,
    // x = spectrum origin world x, y = spectrum origin world z,
    // z = spectrum world span, w = spectrum texture dimension.
    spectrum_params: vec4<f32>,
    // x = debug view mode, yzw reserved.
    water_params1: vec4<f32>,
};

@group(0) @binding(0)
var<uniform> frame: FrameUniforms;

// GPU-resident large/mid ocean field generated by ocean_spectrum.wgsl.
// RGBA layout:
//   R = horizontal displacement x
//   G = height
//   B = horizontal displacement z
//   A = large/mid foam energy
@group(0) @binding(1)
var spectrum_tex: texture_2d<f32>;

// Final FFT tile outputs are bound directly for render-time cascade sampling.
// The filtered field texture is useful for broad/far water and foam, but it is
// too coarse to carry WoWS-style near-camera geometric chop. Sampling the FFT
// cascade tiles directly preserves the short/crossing waves without reverting
// to hand-authored Gerstner displacement.
@group(0) @binding(2)
var fft_primary_tiles: texture_2d<f32>;

@group(0) @binding(3)
var fft_aux_tiles: texture_2d<f32>;

// Derived WoWS-style wave-data texture from ocean_wavedata.wgsl.
// RGBA = height-gradient x/z, local roughness/moment, foam coverage.
@group(0) @binding(4)
var wave_data_tex: texture_2d<f32>;

// Temporal foam/roughness memory from ocean_foam_history.wgsl.
// RGBA = accumulated foam, accumulated roughness, crest memory, breakup mask.
@group(0) @binding(5)
var foam_history_tex: texture_2d<f32>;

struct VertexOut {
    @builtin(position) position: vec4<f32>,
    @location(0) world_pos: vec3<f32>,
    @location(1) base_xz: vec2<f32>,
    @location(2) view_distance: f32,
    @location(3) foam_signal: f32,
    @location(4) field_height: f32,
    @location(5) wave_data: vec4<f32>,
    @location(6) foam_history: vec4<f32>,
};

struct WaveContrib {
    height: f32,
    disp: vec2<f32>,
    slope: vec2<f32>,
    curvature: f32,
};

const TAU: f32 = 6.28318530718;
const G: f32 = 9.81;

// The projected grid must extend beyond the exact framebuffer rectangle.
// Waves horizontally displace vertices after ray/plane intersection; without
// guard coverage those displaced edge vertices expose the clear color at the
// bottom and sides of the frame. The asymmetric bottom guard is intentional:
// near-camera water occupies more vertical screen area than the far horizon.
const GRID_GUARD_X: f32 = 2.70;
const GRID_GUARD_TOP: f32 = 0.62;
const GRID_GUARD_BOTTOM: f32 = 5.10;
const MIN_RAY_PLANE_Y: f32 = 0.00003;

fn debug_signed(v: f32, scale: f32) -> vec3<f32> {
    let x = clamp(v * scale * 0.5 + 0.5, 0.0, 1.0);
    return mix(vec3<f32>(0.02, 0.10, 0.24), vec3<f32>(0.92, 0.94, 0.88), x);
}

fn debug_vec2(v: vec2<f32>, scale: f32) -> vec3<f32> {
    let sx = clamp(v.x * scale * 0.5 + 0.5, 0.0, 1.0);
    let sy = clamp(v.y * scale * 0.5 + 0.5, 0.0, 1.0);
    let mag = clamp(length(v) * scale, 0.0, 1.0);
    return vec3<f32>(sx, mag, sy);
}

fn debug_heat(v: f32) -> vec3<f32> {
    let x = clamp(v, 0.0, 1.0);
    return mix(mix(vec3<f32>(0.02, 0.04, 0.10), vec3<f32>(0.02, 0.40, 0.70), smoothstep(0.0, 0.55, x)), vec3<f32>(0.95, 0.80, 0.30), smoothstep(0.45, 1.0, x));
}

fn debug_visualize(mode: i32, in_data: VertexOut, normal: vec3<f32>, slope_mag: f32, roughness: f32, foam: f32) -> vec3<f32> {
    let displacement = in_data.world_pos.xz - in_data.base_xz;
    let variation = wave_variation(in_data.base_xz);
    let variation_mix = dot(variation, vec4<f32>(0.25));

    if mode == 1 {
        return debug_signed(in_data.world_pos.y - frame.camera_forward_water.w, 0.45);
    }
    if mode == 2 {
        return debug_vec2(displacement, 0.12);
    }
    if mode == 3 {
        return debug_vec2(in_data.wave_data.xy, 1.9);
    }
    if mode == 4 {
        return vec3<f32>(debug_heat(in_data.wave_data.z).rg, clamp(in_data.wave_data.w, 0.0, 1.0));
    }
    if mode == 5 {
        return vec3<f32>(clamp(in_data.foam_history.x, 0.0, 1.0), clamp(in_data.foam_history.y, 0.0, 1.0), clamp(in_data.foam_history.z + in_data.foam_history.w * 0.5, 0.0, 1.0));
    }
    if mode == 6 {
        return vec3<f32>(variation.x, variation.y * 0.75, variation.z * 0.55 + variation.w * 0.35);
    }
    if mode == 7 {
        return vec3<f32>(roughness, foam, clamp(slope_mag * 0.55 + variation_mix * 0.25, 0.0, 1.0));
    }
    return normal * 0.5 + vec3<f32>(0.5);
}

fn empty_wave() -> WaveContrib {
    var w: WaveContrib;
    w.height = 0.0;
    w.disp = vec2<f32>(0.0, 0.0);
    w.slope = vec2<f32>(0.0, 0.0);
    w.curvature = 0.0;
    return w;
}

fn add_wave(a: WaveContrib, b: WaveContrib) -> WaveContrib {
    var r: WaveContrib;
    r.height = a.height + b.height;
    r.disp = a.disp + b.disp;
    r.slope = a.slope + b.slope;
    r.curvature = a.curvature + b.curvature;
    return r;
}

fn scale_wave(w: WaveContrib, k: f32) -> WaveContrib {
    var r: WaveContrib;
    r.height = w.height * k;
    r.disp = w.disp * k;
    r.slope = w.slope * k;
    r.curvature = w.curvature * k;
    return r;
}

fn crest_component(
    p: vec2<f32>,
    dir: vec2<f32>,
    wavelength: f32,
    amplitude: f32,
    speed_scale: f32,
    sharpness: f32,
    phase: f32,
) -> WaveContrib {
    let d = normalize(dir);
    let k = TAU / wavelength;
    let omega = sqrt(G * k) * speed_scale;
    let t = frame.resolution_time_grid.z;

    // Keep this layer coherent. WoWS small waves are dense crest trains riding
    // on FFT water, not domain-warped checkerboard packets.  Use narrow crests
    // with a small second harmonic so height has peaks without folding the mesh.
    let theta = k * dot(p, d) - omega * t + phase;
    let s = sin(theta);
    let c = cos(theta);
    let s2 = sin(theta * 2.0 + phase * 0.37);
    let c2 = cos(theta * 2.0 + phase * 0.37);

    let pos = max(s, 0.0);
    let neg = max(-s, 0.0);
    let crest = pow(smoothstep(0.02, 1.0, pos), sharpness);
    let trough = -0.20 * neg * neg;
    let shoulder = 0.10 * s2;

    let d_crest = select(0.0, sharpness * pow(max(pos, 0.0001), sharpness - 1.0) * c, pos > 0.0);
    let d_trough = select(0.0, 0.40 * neg * c, neg > 0.0);
    let d_height_dtheta = amplitude * (0.66 * c + 0.34 * d_crest + d_trough + 0.20 * c2);

    var w: WaveContrib;
    w.height = amplitude * (0.58 * s + 0.42 * crest + trough + shoulder);
    w.disp = d * (amplitude * 0.018 * c);
    w.slope = d * (d_height_dtheta * k);
    w.curvature = -amplitude * k * k * (0.58 * s + crest * (0.46 + sharpness * 0.10) + shoulder * 0.8);
    return w;
}

fn wind_streak_variation(p: vec2<f32>) -> f32 {
    let wind = normalize(vec2<f32>(0.76, -0.65));
    let cross = vec2<f32>(-wind.y, wind.x);
    let t = frame.resolution_time_grid.z;
    let q = vec2<f32>(dot(p, wind) * 0.0034 + t * 0.020, dot(p, cross) * 0.014 - t * 0.010);
    let r = vec2<f32>(dot(p, wind) * 0.0090 - t * 0.055, dot(p, cross) * 0.028 + t * 0.020);
    return smoothstep(0.18, 0.88, fbm2(q + vec2<f32>(13.0, -41.0)) * 0.65 + fbm2(r + vec2<f32>(-7.0, 19.0)) * 0.35);
}

fn small_wave_bank(p: vec2<f32>, view_distance: f32) -> WaveContrib {
    var w = empty_wave();
    let t = frame.resolution_time_grid.z;
    let variation = wave_variation(p);
    let streak = wind_streak_variation(p);
    let wind = normalize(vec2<f32>(0.76, -0.65));
    let cross = vec2<f32>(-wind.y, wind.x);

    // Smooth low-frequency drift, not per-wave packet gating. The prior domain
    // warped crestlets created visible square/tiling artifacts. These waves are
    // wind-aligned families with small angular spread, closer to the WoWS
    // layering idea: short crests riding on FFT displacement and moments.
    let warp = (fbm2(p * 0.010 + vec2<f32>(t * 0.020, -t * 0.015)) - 0.5) * wind * 5.0
             + (fbm2(p * 0.013 + vec2<f32>(-t * 0.014, t * 0.018)) - 0.5) * cross * 3.0;
    let q = p + warp;

    let near_gate = smoothstep(55.0, 150.0, view_distance);
    let far_gate = 1.0 - smoothstep(2600.0, 7600.0, view_distance);
    let gain = near_gate * far_gate * mix(0.78, 1.26, streak) * mix(0.90, 1.18, variation.z * 0.52 + variation.w * 0.48);

    // Direction spread is deliberately narrow. Equal-strength perpendicular
    // trains read as crosshatch; WoWS reads as wind-aligned rough sea with
    // occasional counter ripples.
    w = add_wave(w, crest_component(q + wind * (t * 3.2), normalize(wind + cross * 0.20), 42.0, 0.145, 1.55, 2.8, 0.9));
    w = add_wave(w, crest_component(q - wind * (t * 1.7), normalize(wind - cross * 0.28), 29.0, 0.110, 2.15, 3.2, 2.7));
    w = add_wave(w, crest_component(q + wind * (t * 5.1), normalize(wind + cross * 0.10), 20.0, 0.076, 2.85, 3.7, 4.1));
    w = add_wave(w, crest_component(q - wind * (t * 4.4), normalize(-wind + cross * 0.18), 15.5, 0.040, 3.60, 4.0, 5.6));
    w = add_wave(w, crest_component(q + wind * (t * 6.8), normalize(wind - cross * 0.08), 11.5, 0.026, 4.35, 4.4, 1.8));

    w = scale_wave(w, gain);
    // Small waves may contribute real peak height only where the grid can carry
    // them. Horizontal displacement stays tiny to avoid folding/projected-grid
    // slabs. Slope/curvature remain strong for normals and foam.
    w.disp *= 0.10;
    w.slope *= 1.05;
    w.curvature *= 1.08;
    return sanitize_direct_wave(w);
}

fn wave_component(
    p: vec2<f32>,
    dir: vec2<f32>,
    wavelength: f32,
    amplitude: f32,
    speed_scale: f32,
    steepness: f32,
    phase: f32,
) -> WaveContrib {
    let d = normalize(dir);
    let k = TAU / wavelength;
    let omega = sqrt(G * k) * speed_scale;
    let theta = k * dot(d, p) - omega * frame.resolution_time_grid.z + phase;
    let s = sin(theta);
    let c = cos(theta);

    var w: WaveContrib;
    w.height = amplitude * s;
    w.disp = d * (steepness * frame.water_params0.y * amplitude * c);
    w.slope = d * (amplitude * k * c);
    w.curvature = -amplitude * k * k * s;
    return w;
}

fn spectrum_detail(p: vec2<f32>) -> WaveContrib {
    var w = empty_wave();
    let t = frame.resolution_time_grid.z;
    let wind = normalize(vec2<f32>(0.76, -0.65));
    let cross = vec2<f32>(-wind.y, wind.x);
    let warp = vec2<f32>(
        fbm2(p * 0.045 + vec2<f32>(t * 0.060, -17.0)),
        fbm2(p * 0.052 + vec2<f32>(31.0, -t * 0.050))
    ) - vec2<f32>(0.5, 0.5);
    let q = p + (wind * warp.x + cross * warp.y) * 3.6;

    // Detail layer: wind-aligned small waves, not a symmetric cross set.
    // This is normal/foam detail only; actual mesh peaks come from the cleaned
    // short crest bank and coherent FFT cascades.
    w = add_wave(w, wave_component(q + wind * ( t * 4.1), normalize(wind + cross * 0.24), 10.5, 0.038, 4.50, 0.18, 1.9));
    w = add_wave(w, wave_component(q - wind * ( t * 3.0), normalize(wind - cross * 0.18),  7.2, 0.030, 5.80, 0.15, 3.7));
    w = add_wave(w, wave_component(q + wind * ( t * 6.3), normalize(wind + cross * 0.08),  5.1, 0.021, 7.20, 0.12, 5.4));
    w = add_wave(w, wave_component(q - wind * ( t * 7.8), normalize(-wind + cross * 0.14),  3.8, 0.013, 8.40, 0.08, 0.6));
    w = add_wave(w, wave_component(q + wind * ( t * 9.0), normalize(wind - cross * 0.06),  2.7, 0.007, 10.0, 0.05, 2.8));
    return w;
}

fn hash21(p: vec2<f32>) -> f32 {
    return fract(sin(dot(p, vec2<f32>(127.1, 311.7))) * 43758.5453123);
}

fn noise2(p: vec2<f32>) -> f32 {
    let i = floor(p);
    let f = fract(p);
    let u = f * f * (vec2<f32>(3.0, 3.0) - 2.0 * f);

    let a = hash21(i + vec2<f32>(0.0, 0.0));
    let b = hash21(i + vec2<f32>(1.0, 0.0));
    let c = hash21(i + vec2<f32>(0.0, 1.0));
    let d = hash21(i + vec2<f32>(1.0, 1.0));

    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}

fn smooth_interp2(f: vec2<f32>) -> vec2<f32> {
    return f * f * f * (f * (f * 6.0 - vec2<f32>(15.0, 15.0)) + vec2<f32>(10.0, 10.0));
}

fn fbm2(p: vec2<f32>) -> f32 {
    var q = p;
    var amp = 0.52;
    var sum = 0.0;
    var norm = 0.0;
    for (var i = 0; i < 4; i = i + 1) {
        sum += noise2(q) * amp;
        norm += amp;
        q = mat2x2<f32>(1.63, 1.12, -1.12, 1.63) * q + vec2<f32>(17.7, -9.2);
        amp *= 0.50;
    }
    return sum / max(norm, 0.0001);
}

fn sea_shadow_variation(p: vec2<f32>) -> f32 {
    // Low-frequency water/cloud shadow proxy. Keep it smooth and subtle: the
    // last version exposed square value-noise blocks across the foreground.
    let t = frame.resolution_time_grid.z;
    let wind = normalize(vec2<f32>(0.76, -0.65));
    let cross = vec2<f32>(-wind.y, wind.x);
    let q = vec2<f32>(dot(p, wind) * 0.0022 + t * 0.010, dot(p, cross) * 0.0034 - t * 0.006);
    let m = fbm2(q + vec2<f32>(4.2, -11.7));
    return mix(0.86, 1.04, smoothstep(0.18, 0.88, m));
}

fn spectrum_texel_size() -> f32 {
    return max(frame.spectrum_params.z / max(frame.spectrum_params.w, 1.0), 0.25);
}

fn wave_variation(p: vec2<f32>) -> vec4<f32> {
    // Smooth stand-in for WoWS variation/space-variation textures.  It should
    // blend wave layers without drawing visible square blocks, so use fbm and
    // conservative ranges instead of raw single-cell value noise.
    let wind = normalize(vec2<f32>(0.76, -0.65));
    let cross = vec2<f32>(-wind.y, wind.x);
    let a = fbm2(vec2<f32>(dot(p, wind) * 0.0012, dot(p, cross) * 0.0017) + vec2<f32>(17.0, 31.0));
    let b = fbm2(vec2<f32>(dot(p, wind) * 0.0030, dot(p, cross) * 0.0044) + vec2<f32>(-43.0, 11.0));
    let c = fbm2(vec2<f32>(dot(p, wind) * 0.0070, dot(p, cross) * 0.0090) + vec2<f32>(9.0, -57.0));
    let large = mix(0.88, 1.04, a);
    let mid = mix(0.92, 1.22, b);
    let shortv = mix(0.96, 1.36, c);
    let micro = mix(0.96, 1.44, smoothstep(0.16, 0.86, b * 0.42 + c * 0.58));
    return vec4<f32>(large, mid, shortv, micro);
}


fn finite_or(v: f32, fallback: f32, limit: f32) -> f32 {
    let good = (v == v) && abs(v) <= limit;
    return select(fallback, clamp(v, -limit, limit), good);
}

fn sanitize_spectrum_field(v: vec4<f32>) -> vec4<f32> {
    return vec4<f32>(
        finite_or(v.x, 0.0, 13.0),
        finite_or(v.y, 0.0, 4.2),
        finite_or(v.z, 0.0, 13.0),
        finite_or(v.w, 0.0, 1.0)
    );
}
fn sample_spectrum_field(base_xz: vec2<f32>) -> vec4<f32> {
    let origin = frame.spectrum_params.xy;
    let span = max(frame.spectrum_params.z, 1.0);
    let n = max(u32(frame.spectrum_params.w), 1u);
    // The field texture is generated in world coordinates over a camera-centered
    // window.  Do not clamp at that window's edge: clamping creates a frozen
    // displacement strip and makes the projected grid visibly stop covering
    // the camera when zoomed in. Repeat the stabilized field instead; the FFT
    // cascades themselves are periodic, so wrapping is the correct ocean-tile
    // behavior until we add larger clipmap rings.
    let uv = fract((base_xz - origin) / span);
    let coord = uv * f32(n);
    let ix = i32(floor(coord.x));
    let iy = i32(floor(coord.y));
    let x0 = ((ix % i32(n)) + i32(n)) % i32(n);
    let y0 = ((iy % i32(n)) + i32(n)) % i32(n);
    let x1 = (x0 + 1) % i32(n);
    let y1 = (y0 + 1) % i32(n);
    let f = smooth_interp2(fract(coord));

    let a = textureLoad(spectrum_tex, vec2<i32>(x0, y0), 0);
    let b = textureLoad(spectrum_tex, vec2<i32>(x1, y0), 0);
    let c = textureLoad(spectrum_tex, vec2<i32>(x0, y1), 0);
    let d = textureLoad(spectrum_tex, vec2<i32>(x1, y1), 0);

    return sanitize_spectrum_field(mix(mix(a, b, f.x), mix(c, d, f.x), f.y));
}

fn sanitize_wave_data(v: vec4<f32>) -> vec4<f32> {
    return vec4<f32>(
        finite_or(v.x, 0.0, 1.4),
        finite_or(v.y, 0.0, 1.4),
        finite_or(v.z, 0.0, 1.0),
        finite_or(v.w, 0.0, 1.0)
    );
}

fn sample_wave_data_field(base_xz: vec2<f32>) -> vec4<f32> {
    let origin = frame.spectrum_params.xy;
    let span = max(frame.spectrum_params.z, 1.0);
    let n = max(u32(frame.spectrum_params.w), 1u);
    let uv = fract((base_xz - origin) / span);
    let coord = uv * f32(n);
    let ix = i32(floor(coord.x));
    let iy = i32(floor(coord.y));
    let x0 = ((ix % i32(n)) + i32(n)) % i32(n);
    let y0 = ((iy % i32(n)) + i32(n)) % i32(n);
    let x1 = (x0 + 1) % i32(n);
    let y1 = (y0 + 1) % i32(n);
    let f = smooth_interp2(fract(coord));

    let a = textureLoad(wave_data_tex, vec2<i32>(x0, y0), 0);
    let b = textureLoad(wave_data_tex, vec2<i32>(x1, y0), 0);
    let c = textureLoad(wave_data_tex, vec2<i32>(x0, y1), 0);
    let d = textureLoad(wave_data_tex, vec2<i32>(x1, y1), 0);

    return sanitize_wave_data(mix(mix(a, b, f.x), mix(c, d, f.x), f.y));
}

fn sanitize_foam_history(v: vec4<f32>) -> vec4<f32> {
    return vec4<f32>(
        finite_or(v.x, 0.0, 1.0),
        finite_or(v.y, 0.0, 1.0),
        finite_or(v.z, 0.0, 1.0),
        finite_or(v.w, 0.0, 1.0)
    );
}

fn sample_foam_history_field(base_xz: vec2<f32>) -> vec4<f32> {
    let origin = frame.spectrum_params.xy;
    let span = max(frame.spectrum_params.z, 1.0);
    let n = max(u32(frame.spectrum_params.w), 1u);
    let uv = fract((base_xz - origin) / span);
    let coord = uv * f32(n);
    let ix = i32(floor(coord.x));
    let iy = i32(floor(coord.y));
    let x0 = ((ix % i32(n)) + i32(n)) % i32(n);
    let y0 = ((iy % i32(n)) + i32(n)) % i32(n);
    let x1 = (x0 + 1) % i32(n);
    let y1 = (y0 + 1) % i32(n);
    let f = smooth_interp2(fract(coord));

    let a = textureLoad(foam_history_tex, vec2<i32>(x0, y0), 0);
    let b = textureLoad(foam_history_tex, vec2<i32>(x1, y0), 0);
    let c = textureLoad(foam_history_tex, vec2<i32>(x0, y1), 0);
    let d = textureLoad(foam_history_tex, vec2<i32>(x1, y1), 0);

    return sanitize_foam_history(mix(mix(a, b, f.x), mix(c, d, f.x), f.y));
}


struct DirectCascadeParams {
    domain: f32,
    height_gain: f32,
    chop_gain: f32,
    slope_scale: f32,
    curvature_gain: f32,
};

fn direct_cascade_params(index: i32) -> DirectCascadeParams {
    var c: DirectCascadeParams;

    if index == 0 {
        // Keep the long swell subordinate.  WoWS rough seas read from many
        // interacting wave bands, not one tall slow roller.
        c.domain = 900.0;
        c.height_gain = 0.024;
        c.chop_gain = 0.42;
        c.slope_scale = 0.90;
        c.curvature_gain = 0.28;
    } else if index == 1 {
        // Mid/cross chop carries more visible geometry than the swell.
        c.domain = 360.0;
        c.height_gain = 0.095;
        c.chop_gain = 0.50;
        c.slope_scale = 2.95;
        c.curvature_gain = 1.18;
    } else if index == 2 {
        // Short waves should be visible in silhouette/geometry close to the
        // camera, but not inflate the ocean into slow hills.
        c.domain = 150.0;
        c.height_gain = 0.105;
        c.chop_gain = 0.34;
        c.slope_scale = 5.85;
        c.curvature_gain = 2.20;
    } else {
        // Micro cascade: mostly normal/slope/crest definition with a small
        // amount of real geometry so the near surface is not flat.
        c.domain = 62.0;
        c.height_gain = 0.026;
        c.chop_gain = 0.08;
        c.slope_scale = 8.20;
        c.curvature_gain = 3.70;
    }

    return c;
}

fn sanitize_direct_tile(v: vec4<f32>) -> vec4<f32> {
    return vec4<f32>(
        finite_or(v.x, 0.0, 96.0),
        finite_or(v.y, 0.0, 96.0),
        finite_or(v.z, 0.0, 96.0),
        finite_or(v.w, 0.0, 96.0)
    );
}

fn direct_load_primary(coord: vec2<i32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> vec4<f32> {
    let x = ((coord.x % mode_dim) + mode_dim) % mode_dim;
    let y_local = ((coord.y % mode_dim) + mode_dim) % mode_dim;
    let y = cascade_index * mode_dim + y_local;
    if y < 0 || y >= total_h {
        return vec4<f32>(0.0, 0.0, 0.0, 0.0);
    }
    return sanitize_direct_tile(textureLoad(fft_primary_tiles, vec2<i32>(x, y), 0));
}

fn direct_load_aux(coord: vec2<i32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> vec4<f32> {
    let x = ((coord.x % mode_dim) + mode_dim) % mode_dim;
    let y_local = ((coord.y % mode_dim) + mode_dim) % mode_dim;
    let y = cascade_index * mode_dim + y_local;
    if y < 0 || y >= total_h {
        return vec4<f32>(0.0, 0.0, 0.0, 0.0);
    }
    return sanitize_direct_tile(textureLoad(fft_aux_tiles, vec2<i32>(x, y), 0));
}

fn direct_bilerp4(a: vec4<f32>, b: vec4<f32>, c: vec4<f32>, d: vec4<f32>, f: vec2<f32>) -> vec4<f32> {
    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

fn direct_sample_primary(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> vec4<f32> {
    let c = direct_cascade_params(cascade_index);
    let coord = fract(p / c.domain) * f32(mode_dim);
    let i0 = vec2<i32>(floor(coord));
    let f = fract(coord);

    let a = direct_load_primary(i0 + vec2<i32>(0, 0), cascade_index, mode_dim, total_h);
    let b = direct_load_primary(i0 + vec2<i32>(1, 0), cascade_index, mode_dim, total_h);
    let c0 = direct_load_primary(i0 + vec2<i32>(0, 1), cascade_index, mode_dim, total_h);
    let d = direct_load_primary(i0 + vec2<i32>(1, 1), cascade_index, mode_dim, total_h);
    return sanitize_direct_tile(direct_bilerp4(a, b, c0, d, f));
}

fn direct_sample_aux(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> vec4<f32> {
    let c = direct_cascade_params(cascade_index);
    let coord = fract(p / c.domain) * f32(mode_dim);
    let i0 = vec2<i32>(floor(coord));
    let f = fract(coord);

    let a = direct_load_aux(i0 + vec2<i32>(0, 0), cascade_index, mode_dim, total_h);
    let b = direct_load_aux(i0 + vec2<i32>(1, 0), cascade_index, mode_dim, total_h);
    let c0 = direct_load_aux(i0 + vec2<i32>(0, 1), cascade_index, mode_dim, total_h);
    let d = direct_load_aux(i0 + vec2<i32>(1, 1), cascade_index, mode_dim, total_h);
    return sanitize_direct_tile(direct_bilerp4(a, b, c0, d, f));
}

fn direct_sample_primary_nearest(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> vec4<f32> {
    let c = direct_cascade_params(cascade_index);
    let coord = fract(p / c.domain) * f32(mode_dim);
    return direct_load_primary(vec2<i32>(floor(coord)), cascade_index, mode_dim, total_h);
}

fn direct_sample_aux_nearest(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> vec4<f32> {
    let c = direct_cascade_params(cascade_index);
    let coord = fract(p / c.domain) * f32(mode_dim);
    return direct_load_aux(vec2<i32>(floor(coord)), cascade_index, mode_dim, total_h);
}

fn rotate2(v: vec2<f32>, angle: f32) -> vec2<f32> {
    let s = sin(angle);
    let c = cos(angle);
    return vec2<f32>(v.x * c - v.y * s, v.x * s + v.y * c);
}

fn rotate_wave(w: WaveContrib, angle: f32) -> WaveContrib {
    var r: WaveContrib;
    r.height = w.height;
    r.disp = rotate2(w.disp, angle);
    r.slope = rotate2(w.slope, angle);
    r.curvature = w.curvature;
    return r;
}

fn direct_cascade_geometry_nearest(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> WaveContrib {
    let c = direct_cascade_params(cascade_index);
    let primary = direct_sample_primary_nearest(p, cascade_index, mode_dim, total_h);
    let aux = direct_sample_aux_nearest(p, cascade_index, mode_dim, total_h);

    var w: WaveContrib;
    w.height = primary.x * c.height_gain;
    w.disp = vec2<f32>(primary.z, aux.x) * c.chop_gain * frame.water_params0.y;
    w.slope = vec2<f32>(0.0, 0.0);
    w.curvature = aux.z * c.curvature_gain;
    return sanitize_direct_wave(w);
}

fn direct_cascade_geometry_smooth(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> WaveContrib {
    let c = direct_cascade_params(cascade_index);
    let primary = direct_sample_primary(p, cascade_index, mode_dim, total_h);
    let aux = direct_sample_aux(p, cascade_index, mode_dim, total_h);

    var w: WaveContrib;
    w.height = primary.x * c.height_gain;
    w.disp = vec2<f32>(primary.z, aux.x) * c.chop_gain * frame.water_params0.y;
    w.slope = vec2<f32>(0.0, 0.0);
    w.curvature = aux.z * c.curvature_gain;
    return sanitize_direct_wave(w);
}

fn direct_cascade_geometry_layered(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32, phase_shift: f32) -> WaveContrib {
    let c = direct_cascade_params(cascade_index);
    let t = frame.resolution_time_grid.z;

    // Keep FFT geometry coherent. The previous rotated secondary/tertiary taps
    // added motion, but they also made visible rectangular blocks when the
    // projected grid sampled short cascades. WoWS uses multiple wave textures,
    // gradients, and variation maps; until those are real independent fields,
    // use one primary FFT sample plus one gentle wind-drifted tap.
    let wind = normalize(vec2<f32>(0.76, -0.65));
    let drift = wind * (t * c.domain * 0.018 * (1.0 + f32(cascade_index) * 0.45));
    let primary = direct_cascade_geometry_smooth(p, cascade_index, mode_dim, total_h);
    let secondary = direct_cascade_geometry_smooth(p + drift + vec2<f32>(phase_shift * 13.7, -phase_shift * 9.1), cascade_index, mode_dim, total_h);

    var w: WaveContrib;
    w.height = primary.height + secondary.height * 0.18;
    w.disp = primary.disp + secondary.disp * 0.10;
    w.slope = primary.slope + secondary.slope * 0.32;
    w.curvature = primary.curvature + secondary.curvature * 0.38;
    return sanitize_direct_wave(w);
}

fn weighted_add_wave(a: WaveContrib, b: WaveContrib, weight: f32) -> WaveContrib {
    var r: WaveContrib;
    r.height = a.height + b.height * weight;
    r.disp = a.disp + b.disp * weight;
    r.slope = a.slope + b.slope * weight;
    r.curvature = a.curvature + b.curvature * weight;
    return r;
}

fn direct_fft_geometry_lod(p: vec2<f32>, view_distance: f32) -> WaveContrib {
    let dims = textureDimensions(fft_primary_tiles, 0);
    let mode_dim = i32(dims.x);
    let total_h = i32(dims.y);

    var w = empty_wave();
    let variation = wave_variation(p);

    // Use nearest sampling only for the far, low-frequency swell where bilinear
    // differences are visually irrelevant.  Mid/short/micro cascades use smooth
    // samples; nearest sampling there was producing the square/plateau artifacts
    // visible in the projected grid. Variation-weighted LODs mimic WoWS'
    // wavesUVScale/wavesUVBias/spaceVariation path: different domains dominate
    // different regions instead of every tile blending uniformly everywhere.
    let w0 = (1.0 - smoothstep(2600.0, 7200.0, view_distance)) * variation.x;
    let w1 = (1.0 - smoothstep(2200.0, 6400.0, view_distance)) * variation.y;
    let w2 = (1.0 - smoothstep(1250.0, 3600.0, view_distance)) * variation.z;
    let w3 = (1.0 - smoothstep(420.0, 1550.0, view_distance)) * variation.w;

    if w0 > 0.001 {
        w = weighted_add_wave(w, direct_cascade_geometry_nearest(p, 0, mode_dim, total_h), w0);
    }
    if w1 > 0.001 {
        w = weighted_add_wave(w, direct_cascade_geometry_layered(p, 1, mode_dim, total_h, 0.75), w1);
    }
    if w2 > 0.001 {
        w = weighted_add_wave(w, direct_cascade_geometry_layered(p, 2, mode_dim, total_h, 0.0), w2);
    }
    if w3 > 0.001 {
        w = weighted_add_wave(w, direct_cascade_geometry_layered(p, 3, mode_dim, total_h, 1.9), w3);
    }

    return sanitize_direct_wave(w);
}

fn sanitize_direct_wave(w: WaveContrib) -> WaveContrib {
    var r: WaveContrib;
    r.height = finite_or(w.height, 0.0, 1.35);
    r.disp = vec2<f32>(finite_or(w.disp.x, 0.0, 2.2), finite_or(w.disp.y, 0.0, 2.2));
    r.slope = vec2<f32>(finite_or(w.slope.x, 0.0, 3.2), finite_or(w.slope.y, 0.0, 3.2));
    r.curvature = finite_or(w.curvature, 0.0, 0.30);
    return r;
}

fn crest_shape_geometry(w: WaveContrib, view_distance: f32) -> WaveContrib {
    // WoWS-like roughness reads as narrow crests, not giant vertical scale.
    // Apply a bounded nonlinear crest lift to coherent FFT geometry, while
    // keeping horizontal chop conservative so the projected grid does not fold.
    var r = sanitize_direct_wave(w);
    let slope_mag = length(r.slope);
    let crest_by_curvature = smoothstep(0.018, 0.145, -r.curvature);
    let crest_by_slope = smoothstep(0.28, 1.80, slope_mag);
    let positive_height = smoothstep(-0.08, 0.34, r.height);
    let near_mid_gate = 1.0 - smoothstep(1450.0, 3600.0, view_distance);
    let crest_mask = crest_by_curvature * crest_by_slope * positive_height * near_mid_gate;

    let peak = min(max(r.height, 0.0) * 0.24 + 0.070, 0.26) * crest_mask;
    r.height = finite_or(r.height + peak, 0.0, 1.80);
    r.disp *= mix(1.0, 0.62, crest_mask);
    r.slope *= 1.0 + crest_mask * 0.50;
    r.curvature = finite_or(r.curvature - crest_mask * 0.035, 0.0, 0.42);
    return r;
}

fn direct_cascade_geometry(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> WaveContrib {
    let c = direct_cascade_params(cascade_index);
    let primary = direct_sample_primary(p, cascade_index, mode_dim, total_h);
    let aux = direct_sample_aux(p, cascade_index, mode_dim, total_h);

    var w: WaveContrib;
    w.height = primary.x * c.height_gain;
    w.disp = vec2<f32>(primary.z, aux.x) * c.chop_gain * frame.water_params0.y;
    w.slope = vec2<f32>(0.0, 0.0);
    w.curvature = aux.z * c.curvature_gain;
    return sanitize_direct_wave(w);
}

fn direct_cascade_wave(p: vec2<f32>, cascade_index: i32, mode_dim: i32, total_h: i32) -> WaveContrib {
    let c = direct_cascade_params(cascade_index);
    let dx = max(c.domain / f32(mode_dim), 0.22);
    var w = direct_cascade_geometry(p, cascade_index, mode_dim, total_h);

    let h_l = direct_cascade_geometry(p - vec2<f32>(dx, 0.0), cascade_index, mode_dim, total_h).height;
    let h_r = direct_cascade_geometry(p + vec2<f32>(dx, 0.0), cascade_index, mode_dim, total_h).height;
    let h_d = direct_cascade_geometry(p - vec2<f32>(0.0, dx), cascade_index, mode_dim, total_h).height;
    let h_u = direct_cascade_geometry(p + vec2<f32>(0.0, dx), cascade_index, mode_dim, total_h).height;
    w.slope = vec2<f32>((h_r - h_l) / (2.0 * dx), (h_u - h_d) / (2.0 * dx)) * c.slope_scale;
    return sanitize_direct_wave(w);
}

fn direct_fft_geometry(p: vec2<f32>) -> WaveContrib {
    let dims = textureDimensions(fft_primary_tiles, 0);
    let mode_dim = i32(dims.x);
    let total_h = i32(dims.y);

    var w = empty_wave();
    w = add_wave(w, direct_cascade_geometry(p, 0, mode_dim, total_h));
    w = add_wave(w, direct_cascade_geometry(p, 1, mode_dim, total_h));
    w = add_wave(w, direct_cascade_geometry(p, 2, mode_dim, total_h));
    w = add_wave(w, direct_cascade_geometry(p, 3, mode_dim, total_h));
    return sanitize_direct_wave(w);
}

fn direct_fft_wave(p: vec2<f32>) -> WaveContrib {
    let dims = textureDimensions(fft_primary_tiles, 0);
    let mode_dim = i32(dims.x);
    let total_h = i32(dims.y);

    var w = empty_wave();
    w = add_wave(w, direct_cascade_wave(p, 0, mode_dim, total_h));
    w = add_wave(w, direct_cascade_wave(p, 1, mode_dim, total_h));
    w = add_wave(w, direct_cascade_wave(p, 2, mode_dim, total_h));
    w = add_wave(w, direct_cascade_wave(p, 3, mode_dim, total_h));
    return sanitize_direct_wave(w);
}

fn projected_grid_uv(vertex_index: u32) -> vec2<f32> {
    let n = max(u32(frame.resolution_time_grid.w), 2u);
    let cell_vertex = vertex_index % 6u;
    let cell_index = vertex_index / 6u;
    let x = cell_index % n;
    let y = cell_index / n;

    var cx: u32 = 0u;
    var cy: u32 = 0u;
    switch cell_vertex {
        case 0u: { cx = 0u; cy = 0u; }
        case 1u: { cx = 1u; cy = 0u; }
        case 2u: { cx = 0u; cy = 1u; }
        case 3u: { cx = 0u; cy = 1u; }
        case 4u: { cx = 1u; cy = 0u; }
        default: { cx = 1u; cy = 1u; }
    }

    return vec2<f32>(f32(x + cx), f32(y + cy)) / f32(n);
}

fn projected_grid_edge_fade(uv: vec2<f32>) -> f32 {
    // Only the outer guard band is damped. The actual visible framebuffer maps
    // well inside this 0..1 grid after the guard expansion, so normal water
    // motion remains intact while the mesh boundary stops pulling inward and
    // revealing the clear color when the camera is close to the ocean.
    let edge = min(min(uv.x, 1.0 - uv.x), min(uv.y, 1.0 - uv.y));
    return smoothstep(0.004, 0.022, edge);
}

fn projected_grid_boundary_pin(uv: vec2<f32>) -> f32 {
    // Projected-grid displacement is correct in the interior, but the outer
    // guard vertices must behave like a skirt.  If they are allowed to project
    // only from their displaced world positions, near-camera zoom and horizontal
    // chop can pull the boundary inward and reveal the clear color.  Pinning
    // only the side and bottom guard bands to their generated NDC coordinates
    // preserves the infinite-water coverage while avoiding a top skirt that
    // would draw water into the sky above the horizon.
    let side_dist = min(uv.x, 1.0 - uv.x);
    let bottom_dist = 1.0 - uv.y;
    let side_gate = smoothstep(0.035, 0.120, uv.y);
    let side_pin = (1.0 - smoothstep(0.002, 0.016, side_dist)) * side_gate;
    let bottom_pin = 1.0 - smoothstep(0.002, 0.020, bottom_dist);
    return clamp(max(side_pin, bottom_pin), 0.0, 1.0);
}

fn projected_grid_ndc(uv: vec2<f32>) -> vec2<f32> {
    let left = -1.0 - GRID_GUARD_X;
    let right = 1.0 + GRID_GUARD_X;
    let top = 1.0 + GRID_GUARD_TOP;
    let bottom = -1.0 - GRID_GUARD_BOTTOM;

    return vec2<f32>(
        left + (right - left) * uv.x,
        top + (bottom - top) * uv.y
    );
}

fn camera_ray_from_ndc(ndc: vec2<f32>) -> vec3<f32> {
    let tan_half_fovy = frame.camera_pos_fov.w;
    let aspect = frame.camera_up_aspect.w;
    let right = frame.camera_right_maxdist.xyz;
    let up = frame.camera_up_aspect.xyz;
    let forward = frame.camera_forward_water.xyz;
    return normalize(
        forward +
        right * (ndc.x * aspect * tan_half_fovy) +
        up * (ndc.y * tan_half_fovy)
    );
}

fn intersect_water_plane(ndc: vec2<f32>) -> vec2<f32> {
    let cam = frame.camera_pos_fov.xyz;
    let dir = camera_ray_from_ndc(ndc);
    let water_y = frame.camera_forward_water.w;
    let max_dist = frame.camera_right_maxdist.w;

    // Use the real water-plane intersection whenever the ray actually hits the
    // water. Earlier versions clamped valid plane intersections to max_dist;
    // that broke the projected-grid guarantee near the horizon and created a
    // visible clipped/capped ocean edge when the camera was zoomed in. max_dist
    // is now only a fallback for rays that do not hit the water plane.
    var t = max_dist;
    if abs(dir.y) > MIN_RAY_PLANE_Y {
        let plane_t = (water_y - cam.y) / dir.y;
        if plane_t > 0.0 {
            t = min(plane_t, max_dist);
        }
    }

    let hit = cam + dir * max(t, 0.0);

    // Camera-relative snap stabilizes distant projected vertices without
    // making the water pattern itself screen-space. The shader still samples
    // the field texture in absolute world coordinates.
    let snap = max(frame.water_params0.x, 0.001);
    return floor(hit.xz / snap) * snap;
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32) -> VertexOut {
    let uv = projected_grid_uv(vertex_index);
    let ndc = projected_grid_ndc(uv);

    let base_xz = intersect_water_plane(ndc);
    let field = sample_spectrum_field(base_xz);
    let wave_data = sample_wave_data_field(base_xz);
    let foam_history = sample_foam_history_field(base_xz);
    let edge_fade = projected_grid_edge_fade(uv);

    let water_y = frame.camera_forward_water.w;
    let base_world = vec3<f32>(base_xz.x, water_y, base_xz.y);
    let base_view_distance = length(base_world - frame.camera_pos_fov.xyz);
    let direct = direct_fft_geometry_lod(base_xz, base_view_distance);

    // Direct FFT tile sampling is a near/mid geometry enhancement now. The
    // filtered field remains the stable broad-ocean base, so we can keep the
    // vertex count reasonable without making the surface read flat.
    let shaped_direct = crest_shape_geometry(direct, base_view_distance);
    let crestlets = small_wave_bank(base_xz, base_view_distance);
    let far_weight = 1.0 - smoothstep(3600.0, 8600.0, base_view_distance);
    // The first few meters under the camera are numerically fragile for a
    // projected grid. Fade geometry there and let the material normal carry the
    // foreground detail; this removes the large broken foreground polygons.
    let near_stability = smoothstep(95.0, 280.0, base_view_distance);
    let direct_weight = far_weight * near_stability;
    let rough_lift = clamp(wave_data.z * 0.070 + foam_history.z * 0.026, 0.0, 0.10) * direct_weight;
    // Sub-grid crest packets were producing foreground square artifacts when
    // applied as full vertex displacement. Gate them out directly under the
    // camera and only let a small amount affect mid-near geometry. Their main
    // role is normals/foam, not projected-grid folding.
    let crestlet_geo_gate = smoothstep(130.0, 360.0, base_view_distance) * (1.0 - smoothstep(1800.0, 5200.0, base_view_distance));
    let geom_disp = mix(field.xz * 0.10, shaped_direct.disp * 0.72 * near_stability, direct_weight) + crestlets.disp * (0.018 * crestlet_geo_gate);
    let geom_h = mix(field.y * 0.055, shaped_direct.height + rough_lift, direct_weight) + crestlets.height * (0.42 * crestlet_geo_gate);

    let world = vec3<f32>(
        base_xz.x + geom_disp.x * edge_fade,
        water_y + geom_h * edge_fade,
        base_xz.y + geom_disp.y * edge_fade
    );

    var out: VertexOut;
    let real_clip = frame.view_proj * vec4<f32>(world, 1.0);
    let boundary_pin = projected_grid_boundary_pin(uv);
    let pinned_z = clamp(real_clip.z, real_clip.w * 0.0001, real_clip.w * 0.9999);
    let pinned_clip = vec4<f32>(ndc.x * real_clip.w, ndc.y * real_clip.w, pinned_z, real_clip.w);
    out.position = vec4<f32>(mix(real_clip.xy, pinned_clip.xy, boundary_pin), mix(real_clip.z, pinned_clip.z, boundary_pin), real_clip.w);
    out.world_pos = world;
    out.base_xz = base_xz;
    out.view_distance = length(world - frame.camera_pos_fov.xyz);
    out.foam_signal = clamp(foam_history.x * 0.66 + foam_history.z * 0.22 + wave_data.w * 0.20 + field.w * 0.030 + smoothstep(0.030, 0.180, -direct.curvature) * direct_weight * 0.13 + smoothstep(0.018, 0.088, -crestlets.curvature) * 0.22, 0.0, 1.0);
    out.field_height = field.y;
    out.wave_data = wave_data;
    out.foam_history = foam_history;
    return out;
}

fn geometric_normal(world_pos: vec3<f32>) -> vec3<f32> {
    var n = normalize(cross(dpdy(world_pos), dpdx(world_pos)));
    if n.y < 0.0 {
        n = -n;
    }
    return n;
}

fn ocean_normal(world_pos: vec3<f32>, base_xz: vec2<f32>, wave_data: vec4<f32>, foam_history: vec4<f32>, view_distance: f32) -> vec3<f32> {
    // Use screen-space derivatives of the displaced projected grid for the main
    // water normal. This preserves FFT-backed geometry in the material without
    // doing an expensive cascade-tile finite difference for every pixel.
    let geom = geometric_normal(world_pos);
    let geom_slope = vec2<f32>(-geom.x, -geom.z) / max(geom.y, 0.18);

    let detail = spectrum_detail(base_xz * 1.05);
    let counter_detail = spectrum_detail(base_xz * vec2<f32>(-0.73, 0.91) + vec2<f32>(37.0, -19.0));
    let cross_detail = spectrum_detail(base_xz * vec2<f32>(0.46, -1.22) + vec2<f32>(-83.0, 41.0));
    let crestlets = small_wave_bank(base_xz, view_distance);
    let rough_memory = max(wave_data.z, foam_history.y * 0.88);
    let coherent_detail_gate = smoothstep(0.020, 0.42, rough_memory + foam_history.z * 0.34);
    // Keep the old detail waves as subtle surface roughness. The domain-warped
    // crestlet layer now supplies the actual small wave peaks, avoiding the
    // visible straight cross-lines from equal-strength sine sets.
    let detail_slope = (detail.slope * 0.30 + counter_detail.slope * 0.20 + cross_detail.slope * 0.12) * frame.water_params0.w * coherent_detail_gate + crestlets.slope * 1.55;
    let moment_slope = wave_data.xy * mix(1.10, 2.35, rough_memory);
    let foam_suppression = 1.0 - foam_history.x * 0.20;
    let slope = (geom_slope * 0.34 + moment_slope) * foam_suppression + detail_slope;
    return normalize(vec3<f32>(-slope.x, 1.0, -slope.y));
}

fn crest_foam(base_xz: vec2<f32>, view_distance: f32, foam_signal: f32, wave_data: vec4<f32>, foam_history: vec4<f32>) -> f32 {
    let detail = spectrum_detail(base_xz * 1.05);
    let counter_detail = spectrum_detail(base_xz * vec2<f32>(-0.73, 0.91) + vec2<f32>(37.0, -19.0));
    let cross_detail = spectrum_detail(base_xz * vec2<f32>(0.46, -1.22) + vec2<f32>(-83.0, 41.0));
    let crestlets = small_wave_bank(base_xz, view_distance);
    let crestlet_breaking = smoothstep(0.22, 0.98, length(crestlets.slope)) * smoothstep(0.020, 0.092, -crestlets.curvature);
    let detail_breaking = smoothstep(0.24, 0.64, length(detail.slope * 0.28 + counter_detail.slope * 0.18 + cross_detail.slope * 0.12 + crestlets.slope * 0.92)) * smoothstep(0.014, 0.050, -(detail.curvature * 0.22 + counter_detail.curvature * 0.12 + cross_detail.curvature * 0.08 + crestlets.curvature * 0.76));

    let t = frame.resolution_time_grid.z;
    let lace = noise2(base_xz * 0.420 + vec2<f32>(-t * 1.10, t * 0.52));
    let breakup = mix(0.55, 1.0, smoothstep(0.30, 0.82, lace));
    let distance_fade = 1.0 - smoothstep(2400.0, 6200.0, view_distance);

    let moment_foam = smoothstep(0.14, 0.60, max(wave_data.z, foam_history.y)) * max(wave_data.w, foam_history.z * 0.42);
    let history_foam = foam_history.x * mix(0.66, 1.00, foam_history.w);
    let instant_foam = foam_signal * 0.14 + moment_foam * 0.16 + detail_breaking * 0.050 + crestlet_breaking * 0.105;
    return clamp((history_foam * 0.60 + instant_foam) * breakup * distance_fade * frame.water_params0.z, 0.0, 0.36);
}

@fragment
fn fs_main(in: VertexOut) -> @location(0) vec4<f32> {
    let cam = frame.camera_pos_fov.xyz;
    let n = ocean_normal(in.world_pos, in.base_xz, in.wave_data, in.foam_history, in.view_distance);
    let view = normalize(cam - in.world_pos);
    let light = normalize(vec3<f32>(-0.42, 0.78, -0.46));
    let half_vec = normalize(light + view);

    let n_dot_v = clamp(dot(n, view), 0.0, 1.0);
    let n_dot_l = clamp(dot(n, light), 0.0, 1.0);
    let n_dot_h = clamp(dot(n, half_vec), 0.0, 1.0);
    let fresnel = 0.020 + 0.980 * pow(1.0 - n_dot_v, 5.0);

    let detail = spectrum_detail(in.base_xz * 1.05);
    let counter_detail = spectrum_detail(in.base_xz * vec2<f32>(-0.73, 0.91) + vec2<f32>(37.0, -19.0));
    let cross_detail = spectrum_detail(in.base_xz * vec2<f32>(0.46, -1.22) + vec2<f32>(-83.0, 41.0));
    let crestlets = small_wave_bank(in.base_xz, in.view_distance);
    let geom_slope_mag = length(vec2<f32>(-n.x, -n.z) / max(n.y, 0.18));
    let material_roughness = max(in.wave_data.z, in.foam_history.y);
    let detail_gate = smoothstep(0.020, 0.42, material_roughness + in.foam_history.z * 0.30);
    let small_wave_energy = length(crestlets.slope) * 1.08 + smoothstep(0.020, 0.092, -crestlets.curvature) * 0.42;
    let slope_mag = (length(detail.slope * 0.24 + counter_detail.slope * 0.17 + cross_detail.slope * 0.10) * detail_gate) + small_wave_energy + geom_slope_mag * 1.12 + material_roughness * 0.72;
    let foam = crest_foam(in.base_xz, in.view_distance, in.foam_signal, in.wave_data, in.foam_history);

    // Darker turbid/absorptive colors. The previous palette was too close to
    // the sky clear color, which erased the wave contrast. WoWS exposes
    // turbidColor/turbidColor2/subSurfaceColor and PMREM reflection controls;
    // this is a compact stand-in until we add real sky/reflection textures.
    let deep = vec3<f32>(0.002, 0.020, 0.032);
    let body = vec3<f32>(0.005, 0.052, 0.066);
    let lit_body = vec3<f32>(0.026, 0.105, 0.098);
    let crest_tint = vec3<f32>(0.050, 0.132, 0.110);
    let horizon_sky = vec3<f32>(0.20, 0.28, 0.31);
    let zenith_sky = vec3<f32>(0.070, 0.145, 0.230);

    let distance_t = smoothstep(260.0, 5200.0, in.view_distance);
    let height_t = clamp(in.field_height * 0.10 + 0.48, 0.0, 1.0);
    let rough_shadow = 1.0 - smoothstep(0.24, 1.25, slope_mag) * (1.0 - n_dot_l) * 0.34;
    let shadow_variation = sea_shadow_variation(in.base_xz);
    var volume = mix(body, deep, distance_t * 0.76);
    volume = mix(volume, lit_body, height_t * 0.26 * n_dot_l);
    volume = mix(volume, crest_tint, smoothstep(0.42, 1.45, slope_mag) * n_dot_l * 0.18);
    volume *= rough_shadow * shadow_variation;

    let refl_dir = reflect(-view, n);
    let sky_t = clamp(refl_dir.y * 0.52 + 0.38, 0.0, 1.0);
    let sky = mix(horizon_sky, zenith_sky, sky_t);

    let roughness = clamp(0.115 + slope_mag * 0.34 + material_roughness * 0.48 + in.foam_history.z * 0.20 + foam * 0.50, 0.100, 0.88);
    let spec_power = mix(190.0, 18.0, roughness);
    let wind_grain = noise2(in.base_xz * vec2<f32>(0.082, 0.38) + vec2<f32>(frame.resolution_time_grid.z * 0.26, -frame.resolution_time_grid.z * 1.24));
    let sparkle_mask = smoothstep(0.72, 0.982, wind_grain) * (1.0 - foam * 0.76) * mix(0.80, 1.42, material_roughness);
    let specular = pow(n_dot_h, spec_power) * (0.055 + sparkle_mask * 0.115) * n_dot_l * (1.0 - foam * 0.92);

    // PMREM-like behavior: rough water should reflect a darker, blurrier sky;
    // only grazing angles get the broad pale horizon reflection.
    let reflection_strength = fresnel * mix(0.20, 0.46, 1.0 - roughness);
    var color = mix(volume, sky, reflection_strength);
    color += specular * vec3<f32>(0.95, 0.88, 0.70);

    let foam_color = vec3<f32>(0.42, 0.48, 0.44);
    color = mix(color, foam_color, foam);

    let aerial = smoothstep(5200.0, 16000.0, in.view_distance);
    color = mix(color, horizon_sky * 0.48, aerial * 0.06);

    // Stronger contrast than the previous patch.  The old tonemap/gamma path
    // lifted the whole image into light blue/white and hid wave variation.
    color = max((color - vec3<f32>(0.012, 0.016, 0.018)) * 1.52, vec3<f32>(0.0, 0.0, 0.0));
    color = color / (color + vec3<f32>(0.60, 0.64, 0.66));
    color = pow(max(color, vec3<f32>(0.0, 0.0, 0.0)), vec3<f32>(1.0 / 2.15));

    let debug_mode = i32(frame.water_params1.x + 0.5);
    if debug_mode != 0 {
        return vec4<f32>(debug_visualize(debug_mode, in, n, slope_mag, roughness, foam), 1.0);
    }

    return vec4<f32>(color, 1.0);
}
