package ocean

import (
	"math"
	"math/cmplx"
	"math/rand"
)

const gravity = 9.81

// phillipsSpectrum computes the Phillips spectrum value for a given wave vector (kx, kz) and wind parameters.
func phillipsSpectrum(kx, kz, windX, windZ, windSpeed, amplitude float64) (p float64) {
	var k2 float64 = kx*kx + kz*kz
	if k2 < 1e-8 {
		return 0
	}

	var (
		k            float64 = math.Sqrt(k2)
		khatX, khatZ float64 = kx / k, kz / k
		kw           float64 = khatX*windX + khatZ*windZ
		L            float64 = windSpeed * windSpeed / gravity // Largest possible wave generated by a steady wind.
	)

	// Suppress tiny waves so the base mesh is not all noise.
	var (
		smallWaveDamping float64 = 0.0015
		damping          float64 = math.Exp(-k2 * smallWaveDamping * smallWaveDamping)
	)

	// Phillips spectrum.
	p = amplitude * math.Exp(-1.0/(k2*L*L)) / (k2 * k2) * (kw * kw) * damping

	// Reduce waves traveling directly against the wind, but do not remove them entirely.
	if kw < 0 {
		p *= 0.08
	}

	return
}

func gaussian(rng *rand.Rand) (gauss float64) {
	// Box-Muller transform.
	gauss = math.Sqrt(-2*math.Log(math.Max(rng.Float64(), 1e-12))) * math.Cos(2*math.Pi*rng.Float64())
	return
}

func h0FromSpectrum(rng *rand.Rand, p float64) (h0 complex128) {
	var scale float64 = math.Sqrt(p) / math.Sqrt2
	h0 = complex(gaussian(rng)*scale, gaussian(rng)*scale)
	return
}

func omega(k float64) (o float64) {
	if k < 1e-6 {
		return
	}

	o = math.Sqrt(gravity * k)
	return
}

func expI(theta float64) complex128 {
	return cmplx.Exp(complex(0, theta))
}

func negativeWaveIndex(x, z, n int) int {
	return ((n-z)%n)*n + ((n - x) % n)
}

func spectralFields(h complex128, kx, kz, kLen, choppiness float64) (height, slopeX, slopeZ, dispX, dispZ complex128) {
	height = h
	slopeX = complex(0, kx) * h
	slopeZ = complex(0, kz) * h

	if kLen > 1e-6 {
		dispX = complex(0, -kx/kLen*choppiness) * h
		dispZ = complex(0, -kz/kLen*choppiness) * h
	}

	return
}

func surfacePointAndNormal(baseX, baseZ float32, height, slopeX, slopeZ, dispX, dispZ float64) (px, py, pz, nx, ny, nz float32) {
	px = baseX + float32(dispX)
	py = float32(height)
	pz = baseZ + float32(dispZ)

	nx = float32(-slopeX)
	ny = 1
	nz = float32(-slopeZ)

	var invLen float32 = float32(1.0 / math.Sqrt(float64(nx*nx+ny*ny+nz*nz)))
	nx *= invLen
	ny *= invLen
	nz *= invLen

	return
}
